#!/bin/bash

# Rclone-Arr-Setup Deployment Script
# Supports: Ubuntu, Debian

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}=================================================${NC}"
echo -e "${BLUE}       Rclone-Arr-Setup Auto-Deployer           ${NC}"
echo -e "${BLUE}=================================================${NC}"

# 1. Check Root/Sudo
if [ "$EUID" -ne 0 ]; then
  echo -e "${YELLOW}Please run this script with sudo or as root.${NC}"
  echo "Usage: sudo ./deploy.sh"
  exit 1
fi

# 2. Update System
echo -e "\n${GREEN}[1/7] Updating System Repositories...${NC}"
apt-get update -qq

# 3. Check & Install Docker
echo -e "\n${GREEN}[2/7] Checking Docker Installation...${NC}"

if ! command -v docker &> /dev/null; then
    echo -e "${YELLOW}Docker not found. Installing Docker...${NC}"
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh
    rm get-docker.sh
    echo -e "${GREEN}Docker installed successfully.${NC}"
else
    echo -e "${GREEN}Docker is already installed.${NC}"
fi

# Install Docker Compose Plugin if missing
if ! docker compose version &> /dev/null; then
    echo -e "${YELLOW}Docker Compose plugin not found. Installing...${NC}"
    apt-get install -y docker-compose-plugin
else
    echo -e "${GREEN}Docker Compose is ready.${NC}"
fi

# 4. Configure Environment Variables
echo -e "\n${GREEN}[3/7] Configuring Project Environment...${NC}"

# Check if we are in the project folder
if [ ! -f "docker-compose.yml" ]; then
    echo -e "${YELLOW}docker-compose.yml not found. Cloning repository...${NC}"

    # Install git if missing
    if ! command -v git &> /dev/null; then
        apt-get install -y git
    fi

    git clone https://github.com/vinayak-7-0-3/Rclone-Arr-Setup.git
    cd Rclone-Arr-Setup || exit 1
    echo -e "${GREEN}Cloned and entered repository.${NC}"
fi

# Get the directory where the script is located (should be repo root)
REPO_ROOT=$(pwd)
CURRENT_USER=${SUDO_USER:-$USER}
USER_HOME=$(eval echo ~$CURRENT_USER)

echo -e "Project Root detected as: ${BLUE}$REPO_ROOT${NC}"

# Ask for Rclone Remote Name
echo -e "\n${YELLOW}Step 3a: Rclone Configuration${NC}"
read -p "Enter your Rclone Remote Name (e.g., 'drive'): " INPUT_REMOTE
RCLONE_REMOTE=${INPUT_REMOTE:-drive}

# Ask for Rclone WebUI Credentials
echo -e "\n${YELLOW}Step 3b: Security${NC}"
read -p "Create a username for Rclone WebUI [admin]: " INPUT_USER
RCLONE_USER=${INPUT_USER:-admin}

read -p "Create a password for Rclone WebUI [password]: " INPUT_PASS
RCLONE_PASS=${INPUT_PASS:-password}

# Generate/Ask for RPC Secret
RANDOM_SECRET=$(openssl rand -hex 12)
read -p "Enter RPC Secret for Aria2 (Press Enter to generate random): " INPUT_RPC
RPC_SECRET=${INPUT_RPC:-$RANDOM_SECRET}

# Generate/Ask for Encryption Key for Homarr
RANDOM_KEY=$(openssl rand -hex 32)
read -p "Enter Homarr Encryption Key (Press Enter to generate random): " INPUT_KEY
HOMARR_KEY=${INPUT_KEY:-$RANDOM_KEY}

# Set Downloads Folder
DOWNLOADS_FOLDER="$USER_HOME/downloads"
echo -e "\nSetting downloads folder to: ${BLUE}$DOWNLOADS_FOLDER${NC}"
mkdir -p "$DOWNLOADS_FOLDER"
chown -R "$CURRENT_USER:$CURRENT_USER" "$DOWNLOADS_FOLDER"

# Create .env file
echo -e "\n${GREEN}Generating .env file...${NC}"
cat > .env <<EOL
# Generated by deploy.sh

# Storage Paths
MEDIA_SERVER_ROOT=$REPO_ROOT
DOWNLOADS_FOLDER=$DOWNLOADS_FOLDER

# Rclone Configuration
RCLONE_REMOTE=$RCLONE_REMOTE
RCLONE_USER=$RCLONE_USER
RCLONE_PASS=$RCLONE_PASS

# Network
DOCKER_NETWORK=nginx_network

# Security
SECRET_ENCRYPTION_KEY=$HOMARR_KEY
RPC_SECRET=$RPC_SECRET
EOL

# Fix permissions for .env so regular user can read it
chown "$CURRENT_USER:$CURRENT_USER" .env

echo -e "${GREEN}.env file created successfully!${NC}"

# 5. Directory Structure
echo -e "\n${GREEN}[4/7] Creating Directory Structure...${NC}"
mkdir -p configs/rclone
mkdir -p configs/aria2
mkdir -p configs/radarr
mkdir -p configs/prowlarr
mkdir -p configs/qbittorrent
mkdir -p configs/aria2
mkdir -p configs/homarr
mkdir -p configs/jellyfin
mkdir -p logs
mkdir -p scripts

# Make scripts executable
chmod +x scripts/*.sh 2>/dev/null || true
chown -R "$CURRENT_USER:$CURRENT_USER" configs logs scripts

# Fix Log Permissions (Crucial for Docker containers running as non-root)
# qBittorrent (user 1000) needs to write to this folder
chmod -R 777 logs

 # Ensure Aria2 config exists with the correct hook
 if [ ! -f configs/aria2/aria2.conf ]; then
     echo "Creating default Aria2 config..."
     cat <<EOF > configs/aria2/aria2.conf
dir=/downloads
rpc-secret=${RPC_SECRET}
enable-rpc=true
rpc-listen-all=true
rpc-listen-port=6800
rpc-allow-origin-all=true
on-download-complete=/scripts/aria_manage.sh
input-file=/config/aria2.session
save-session=/config/aria2.session
save-session-interval=60
force-save=true
log=/logs/aria2.log
log-level=notice
EOF
 else
     # Update existing config if hook is missing
     if ! grep -q "on-download-complete" configs/aria2/aria2.conf; then
         echo "on-download-complete=/scripts/aria_manage.sh" >> configs/aria2/aria2.conf
         echo "Updated Aria2 config with automation hook."
     fi
 fi

# 6. Rclone Config Setup
echo -e "\n${GREEN}[5/7] Setting up Rclone Config...${NC}"
CONFIG_FILE="configs/rclone/rclone.conf"

if [ -f "$CONFIG_FILE" ]; then
    echo -e "${BLUE}Existing rclone.conf found. Skipping setup.${NC}"
else
    echo -e "${YELLOW}No rclone.conf found.${NC}"
    echo "1) I have an existing rclone.conf content (Paste it)"
    echo "2) I want to run the Config Wizard (Create New)"
    read -p "Select option [1/2]: " OPTION

    if [ "$OPTION" == "1" ]; then
        echo -e "${YELLOW}Paste your config content below. Press Ctrl+D when finished:${NC}"
        cat > "$CONFIG_FILE"
        echo -e "${GREEN}Config saved to: $REPO_ROOT/$CONFIG_FILE${NC}"
    else
        echo -e "${BLUE}Starting Rclone Wizard...${NC}"
        echo -e "${YELLOW}IMPORTANT: If asked for auto-config, say NO (n) because this is a headless server.${NC}"
        # We run this as the sudo user to avoid permission issues with the created file
        docker run --rm -it -v "$REPO_ROOT/configs/rclone:/config/rclone" rclone/rclone config --config /config/rclone/rclone.conf
        echo -e "${GREEN}Config saved to: $REPO_ROOT/$CONFIG_FILE${NC}"
    fi
fi

# Fix config permissions
chown "$CURRENT_USER:$CURRENT_USER" "$CONFIG_FILE" 2>/dev/null

# Smart Fix: Check if Remote Name matches Config
# We grep the first line starting with '[' to find the actual remote name in the file
ACTUAL_REMOTE_NAME=$(grep -m 1 "^\[" "$CONFIG_FILE" | tr -d '[]')

if [ ! -z "$ACTUAL_REMOTE_NAME" ] && [ "$ACTUAL_REMOTE_NAME" != "$RCLONE_REMOTE" ]; then
    echo -e "\n${YELLOW}WARNING: Mismatch detected!${NC}"
    echo "You entered remote name: '$RCLONE_REMOTE'"
    echo "But your config file has: '$ACTUAL_REMOTE_NAME'"
    echo -e "${GREEN}Auto-correcting .env file to use '$ACTUAL_REMOTE_NAME'...${NC}"

    # Update .env using sed
    sed -i "s/RCLONE_REMOTE=$RCLONE_REMOTE/RCLONE_REMOTE=$ACTUAL_REMOTE_NAME/" .env

    # Update our variable for the script execution
    RCLONE_REMOTE=$ACTUAL_REMOTE_NAME
fi

# 7. Start Services
echo -e "\n${GREEN}[6/7] Starting Services...${NC}"

# Create network if not exists
if ! docker network inspect nginx_network &>/dev/null; then
    docker network create nginx_network
    echo -e "Created docker network: nginx_network"
fi

# Service Selection Logic
CORE_SERVICES="rclone homarr"
OPTIONAL_SERVICES=("radarr" "prowlarr" "qbittorrent" "aria2" "ariang" "jellyseerr" "profilarr")

echo -e "\n${BLUE}Installation Mode:${NC}"
echo "1) Full Installation (Install Everything)"
echo "2) Custom Installation (Select apps to SKIP)"
read -p "Select option [1]: " INSTALL_MODE

if [ "$INSTALL_MODE" == "2" ]; then
    echo -e "\n${YELLOW}Custom Installation Selected.${NC}"
    echo "The following core services will ALWAYS be installed: $CORE_SERVICES"
    echo -e "\nSelect the apps you do NOT want to install:"

    # List optional services
    for i in "${!OPTIONAL_SERVICES[@]}"; do
        echo "$((i+1)). ${OPTIONAL_SERVICES[$i]}"
    done

    echo -e "\nEnter the numbers of the apps to SKIP (separated by space)."
    echo "Example: To skip Radarr and Jellyfin, type: 1 7"
    read -p "Skip apps: " SKIP_INDICES

    # Build list of services to run
    SERVICES_TO_RUN="$CORE_SERVICES"

    # Loop through all optional services
    for i in "${!OPTIONAL_SERVICES[@]}"; do
        SERVICE_NUM=$((i+1))
        SERVICE_NAME="${OPTIONAL_SERVICES[$i]}"

        # Check if this index was skipped
        # We add spaces around the list to match whole numbers (e.g. avoid matching '1' inside '10')
        if [[ " $SKIP_INDICES " =~ " $SERVICE_NUM " ]]; then
            echo -e "${RED}Skipping $SERVICE_NAME${NC}"
        else
            SERVICES_TO_RUN="$SERVICES_TO_RUN $SERVICE_NAME"
            echo -e "${GREEN}Adding $SERVICE_NAME${NC}"
        fi
    done

    echo -e "\nStarting specific services: $SERVICES_TO_RUN"
    docker compose up -d $SERVICES_TO_RUN

else
    echo -e "\n${GREEN}Starting ALL services...${NC}"
    docker compose up -d
fi

echo -e "\n${GREEN}[7/7] Deployment Complete!${NC}"

# Get External IP Address (for Google Cloud / VPS)
# We try to curl a public service. If it fails, we fall back to the internal IP.
PUBLIC_IP=$(curl -s https://api.ipify.org || hostname -I | awk '{print $1}')
IP_ADDRESS=${PUBLIC_IP:-localhost}

echo -e "\n${BLUE}=================================================${NC}"
echo -e "${BLUE}       Access Your Services                     ${NC}"
echo -e "${BLUE}=================================================${NC}"
echo -e "Homarr (Dashboard) : http://$IP_ADDRESS:7575"
echo -e "Jellyfin (Stream)  : http://$IP_ADDRESS:8096"
echo -e "Jellyseerr (Request): http://$IP_ADDRESS:5055"
echo -e "Radarr             : http://$IP_ADDRESS:7878"
echo -e "qBittorrent        : http://$IP_ADDRESS:8080"
echo -e "Rclone WebUI       : http://$IP_ADDRESS:5572"
echo -e "${BLUE}=================================================${NC}"
echo -e "Login Credentials:"
echo -e "qBittorrent : admin / adminadmin"
echo -e "Rclone WebUI: $RCLONE_USER / $RCLONE_PASS"
echo -e "-------------------------------------------------"
echo -e "Generated Keys (Saved in .env):"
echo -e "Homarr Encryption Key: $HOMARR_KEY"
echo -e "Aria2 RPC Secret     : $RPC_SECRET"
echo -e "${BLUE}=================================================${NC}"
