#!/bin/bash

# Rclone-Arr-Setup Deployment Script
# Supports: Ubuntu, Debian

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}=================================================${NC}"
echo -e "${BLUE}       Rclone-Arr-Setup Auto-Deployer           ${NC}"
echo -e "${BLUE}=================================================${NC}"

# 1. Check Root/Sudo
if [ "$EUID" -ne 0 ]; then
  echo -e "${YELLOW}Please run this script with sudo or as root.${NC}"
  echo "Usage: sudo ./deploy.sh"
  exit 1
fi

# 2. Update System
echo -e "\n${GREEN}[1/7] Updating System Repositories...${NC}"
apt-get update -qq

# 3. Check & Install Docker
echo -e "\n${GREEN}[2/7] Checking Docker Installation...${NC}"

if ! command -v docker &> /dev/null; then
    echo -e "${YELLOW}Docker not found. Installing Docker...${NC}"
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh
    rm get-docker.sh
    echo -e "${GREEN}Docker installed successfully.${NC}"
else
    echo -e "${GREEN}Docker is already installed.${NC}"
fi

# Install Docker Compose Plugin if missing
if ! docker compose version &> /dev/null; then
    echo -e "${YELLOW}Docker Compose plugin not found. Installing...${NC}"
    apt-get install -y docker-compose-plugin
else
    echo -e "${GREEN}Docker Compose is ready.${NC}"
fi

# 4. Configure Environment Variables
echo -e "\n${GREEN}[3/7] Configuring Project Environment...${NC}"

# Get the directory where the script is located (should be repo root)
REPO_ROOT=$(pwd)
CURRENT_USER=${SUDO_USER:-$USER}
USER_HOME=$(eval echo ~$CURRENT_USER)

echo -e "Project Root detected as: ${BLUE}$REPO_ROOT${NC}"

# Ask for Rclone Remote Name
echo -e "\n${YELLOW}Step 3a: Rclone Configuration${NC}"
read -p "Enter your Rclone Remote Name (e.g., 'drive'): " INPUT_REMOTE
RCLONE_REMOTE=${INPUT_REMOTE:-drive}

# Ask for Rclone WebUI Credentials
echo -e "\n${YELLOW}Step 3b: Security${NC}"
read -p "Create a username for Rclone WebUI [admin]: " INPUT_USER
RCLONE_USER=${INPUT_USER:-admin}

read -p "Create a password for Rclone WebUI [password]: " INPUT_PASS
RCLONE_PASS=${INPUT_PASS:-password}

# Generate/Ask for RPC Secret
RANDOM_SECRET=$(openssl rand -hex 12)
read -p "Enter RPC Secret for Aria2 (Press Enter to generate random): " INPUT_RPC
RPC_SECRET=${INPUT_RPC:-$RANDOM_SECRET}

# Generate Encryption Key for Homarr
HOMARR_KEY=$(openssl rand -hex 32)

# Set Downloads Folder
DOWNLOADS_FOLDER="$USER_HOME/downloads"
echo -e "\nSetting downloads folder to: ${BLUE}$DOWNLOADS_FOLDER${NC}"
mkdir -p "$DOWNLOADS_FOLDER"
chown -R "$CURRENT_USER:$CURRENT_USER" "$DOWNLOADS_FOLDER"

# Create .env file
echo -e "\n${GREEN}Generating .env file...${NC}"
cat > .env <<EOL
# Generated by deploy.sh

# Storage Paths
MEDIA_SERVER_ROOT=$REPO_ROOT
DOWNLOADS_FOLDER=$DOWNLOADS_FOLDER

# Rclone Configuration
RCLONE_REMOTE=$RCLONE_REMOTE
RCLONE_USER=$RCLONE_USER
RCLONE_PASS=$RCLONE_PASS

# Network
DOCKER_NETWORK=nginx_network

# Security
SECRET_ENCRYPTION_KEY=$HOMARR_KEY
RPC_SECRET=$RPC_SECRET
EOL

# Fix permissions for .env so regular user can read it
chown "$CURRENT_USER:$CURRENT_USER" .env

echo -e "${GREEN}.env file created successfully!${NC}"

# 5. Directory Structure
echo -e "\n${GREEN}[4/7] Creating Directory Structure...${NC}"
mkdir -p configs/rclone
mkdir -p configs/aria2
mkdir -p configs/radarr
mkdir -p configs/prowlarr
mkdir -p configs/qbittorrent
mkdir -p configs/homarr
mkdir -p configs/jellyfin
mkdir -p logs
mkdir -p scripts

# Make scripts executable
chmod +x scripts/*.sh 2>/dev/null || true
chown -R "$CURRENT_USER:$CURRENT_USER" configs logs scripts

# 6. Rclone Config Setup
echo -e "\n${GREEN}[5/7] Setting up Rclone Config...${NC}"
CONFIG_FILE="configs/rclone/rclone.conf"

if [ -f "$CONFIG_FILE" ]; then
    echo -e "${BLUE}Existing rclone.conf found. Skipping setup.${NC}"
else
    echo -e "${YELLOW}No rclone.conf found.${NC}"
    echo "1) I have an existing rclone.conf content (Paste it)"
    echo "2) I want to run the Config Wizard (Create New)"
    read -p "Select option [1/2]: " OPTION

    if [ "$OPTION" == "1" ]; then
        echo -e "${YELLOW}Paste your config content below. Press Ctrl+D when finished:${NC}"
        cat > "$CONFIG_FILE"
        echo -e "${GREEN}Config saved to $CONFIG_FILE${NC}"
    else
        echo -e "${BLUE}Starting Rclone Wizard...${NC}"
        echo -e "${YELLOW}IMPORTANT: If asked for auto-config, say NO (n) because this is a headless server.${NC}"
        # We run this as the sudo user to avoid permission issues with the created file
        docker run --rm -it -v "$REPO_ROOT/configs/rclone:/config/rclone" rclone/rclone config --config /config/rclone/rclone.conf
    fi
fi

# Fix config permissions
chown "$CURRENT_USER:$CURRENT_USER" "$CONFIG_FILE" 2>/dev/null

# 7. Start Services
echo -e "\n${GREEN}[6/7] Starting Services...${NC}"

# Create network if not exists
if ! docker network inspect nginx_network &>/dev/null; then
    docker network create nginx_network
    echo -e "Created docker network: nginx_network"
fi

# Run Docker Compose
docker compose up -d

echo -e "\n${GREEN}[7/7] Deployment Complete!${NC}"

# Get IP Address
IP_ADDRESS=$(hostname -I | awk '{print $1}')

echo -e "\n${BLUE}=================================================${NC}"
echo -e "${BLUE}       Access Your Services                     ${NC}"
echo -e "${BLUE}=================================================${NC}"
echo -e "Homarr (Dashboard) : http://$IP_ADDRESS:7575"
echo -e "Jellyfin (Stream)  : http://$IP_ADDRESS:8096"
echo -e "Jellyseerr (Request): http://$IP_ADDRESS:5055"
echo -e "Radarr             : http://$IP_ADDRESS:7878"
echo -e "qBittorrent        : http://$IP_ADDRESS:8080"
echo -e "Rclone WebUI       : http://$IP_ADDRESS:5572"
echo -e "${BLUE}=================================================${NC}"
echo -e "Login Credentials:"
echo -e "qBittorrent : admin / adminadmin"
echo -e "Rclone WebUI: $RCLONE_USER / $RCLONE_PASS"
echo -e "${BLUE}=================================================${NC}"
