#!/bin/bash

# Rclone-Arr-Setup Deployment Script
# Supports: Ubuntu, Debian

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}=================================================${NC}"
echo -e "${BLUE}       Rclone-Arr-Setup Auto-Deployer           ${NC}"
echo -e "${BLUE}=================================================${NC}"

# 1. Check Root/Sudo
if [ "$EUID" -ne 0 ]; then
  echo -e "${YELLOW}Please run this script with sudo or as root.${NC}"
  echo "Usage: sudo ./deploy.sh"
  exit 1
fi

# 2. Update System
echo -e "\n${GREEN}[1/7] Updating System Repositories...${NC}"
apt-get update -qq

# 3. Check & Install Docker
echo -e "\n${GREEN}[2/7] Checking Docker Installation...${NC}"

if ! command -v docker &> /dev/null; then
    echo -e "${YELLOW}Docker not found. Installing Docker...${NC}"
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh
    rm get-docker.sh
    echo -e "${GREEN}Docker installed successfully.${NC}"
else
    echo -e "${GREEN}Docker is already installed.${NC}"
fi

# Install Docker Compose Plugin if missing
if ! docker compose version &> /dev/null; then
    echo -e "${YELLOW}Docker Compose plugin not found. Installing...${NC}"
    apt-get install -y docker-compose-plugin
else
    echo -e "${GREEN}Docker Compose is ready.${NC}"
fi

# 4. Configure Environment Variables
echo -e "\n${GREEN}[3/7] Configuring Project Environment...${NC}"

# Check if we are in the project folder
if [ ! -f "docker-compose.yml" ]; then
    echo -e "${YELLOW}docker-compose.yml not found. Cloning repository...${NC}"

    # Install git if missing
    if ! command -v git &> /dev/null; then
        apt-get install -y git
    fi

    git clone https://github.com/vinayak-7-0-3/Rclone-Arr-Setup.git
    cd Rclone-Arr-Setup || exit 1
    echo -e "${GREEN}Cloned and entered repository.${NC}"
fi

# Get the directory where the script is located (should be repo root)
REPO_ROOT=$(pwd)
CURRENT_USER=${SUDO_USER:-$USER}
USER_HOME=$(eval echo ~$CURRENT_USER)

echo -e "Project Root detected as: ${BLUE}$REPO_ROOT${NC}"

# Ask for Rclone Remote Name
echo -e "\n${YELLOW}Step 3a: Rclone Configuration${NC}"
read -p "Enter your Rclone Remote Name (e.g., 'drive'): " INPUT_REMOTE
RCLONE_REMOTE=${INPUT_REMOTE:-drive}

# Ask for Rclone WebUI Credentials
echo -e "\n${YELLOW}Step 3b: Security${NC}"
read -p "Create a username for Rclone WebUI [admin]: " INPUT_USER
RCLONE_USER=${INPUT_USER:-admin}

read -p "Create a password for Rclone WebUI [password]: " INPUT_PASS
RCLONE_PASS=${INPUT_PASS:-password}

# Generate/Ask for RPC Secret
RANDOM_SECRET=$(openssl rand -hex 12)
read -p "Enter RPC Secret for Aria2 (Press Enter to generate random): " INPUT_RPC
RPC_SECRET=${INPUT_RPC:-$RANDOM_SECRET}

# Generate/Ask for Encryption Key for Homarr
RANDOM_KEY=$(openssl rand -hex 32)
read -p "Enter Homarr Encryption Key (Press Enter to generate random): " INPUT_KEY
HOMARR_KEY=${INPUT_KEY:-$RANDOM_KEY}

# Ask for JDownloader 2 Mode
echo -e "\n${YELLOW}Step 3c: JDownloader 2 Configuration${NC}"
echo "1) Standard Mode (VNC Web Interface + Optional MyJDownloader)"
echo "2) Headless Mode (No Web/VNC, Saves RAM, REQUIRES MyJDownloader Account)"
read -p "Select Mode [1/2] (Default: 1): " JD_MODE

JD_HEADLESS=0
JD_EMAIL=""
JD_PASSWORD=""
JD_DEVICE="JDownloader-Docker"

if [ "$JD_MODE" == "2" ]; then
    echo -e "${BLUE}Headless Mode Selected. You MUST provide MyJDownloader credentials.${NC}"
    JD_HEADLESS=1

    while [ -z "$JD_EMAIL" ]; do
        read -p "Enter MyJDownloader Email: " JD_EMAIL
    done

    while [ -z "$JD_PASSWORD" ]; do
        read -s -p "Enter MyJDownloader Password: " JD_PASSWORD
        echo ""
    done

    read -p "Enter Device Name [JDownloader-Docker]: " INPUT_DEVICE
    JD_DEVICE=${INPUT_DEVICE:-JDownloader-Docker}
else
    echo -e "${BLUE}Standard Mode Selected.${NC}"
fi

# Set Downloads Folder
DOWNLOADS_FOLDER="$USER_HOME/downloads"
echo -e "\nSetting downloads folder to: ${BLUE}$DOWNLOADS_FOLDER${NC}"
mkdir -p "$DOWNLOADS_FOLDER"
chown -R "$CURRENT_USER:$CURRENT_USER" "$DOWNLOADS_FOLDER"

# Create .env file
echo -e "\n${GREEN}Generating .env file...${NC}"
cat > .env <<EOL
# Generated by deploy.sh

# Storage Paths
MEDIA_SERVER_ROOT=$REPO_ROOT
DOWNLOADS_FOLDER=$DOWNLOADS_FOLDER

# Rclone Configuration
RCLONE_REMOTE=$RCLONE_REMOTE
RCLONE_USER=$RCLONE_USER
RCLONE_PASS=$RCLONE_PASS

# Network
DOCKER_NETWORK=nginx_network

# Security
SECRET_ENCRYPTION_KEY=$HOMARR_KEY
RPC_SECRET=$RPC_SECRET

# JDownloader Configuration
JDOWNLOADER_HEADLESS=$JD_HEADLESS
MYJDOWNLOADER_EMAIL=$JD_EMAIL
MYJDOWNLOADER_PASSWORD=$JD_PASSWORD
MYJDOWNLOADER_DEVICE_NAME=$JD_DEVICE
EOL

# Fix permissions for .env so regular user can read it
chown "$CURRENT_USER:$CURRENT_USER" .env

echo -e "${GREEN}.env file created successfully!${NC}"

# 5. Directory Structure
echo -e "\n${GREEN}[4/7] Creating Directory Structure...${NC}"
mkdir -p configs/rclone
mkdir -p configs/aria2
mkdir -p configs/radarr
mkdir -p configs/prowlarr
mkdir -p configs/qbittorrent
mkdir -p configs/aria2
mkdir -p configs/homarr
mkdir -p configs/jellyfin
mkdir -p configs/jdownloader
mkdir -p configs/profilarr
mkdir -p mount
mkdir -p logs
mkdir -p scripts

# Make scripts executable
chmod +x scripts/*.sh 2>/dev/null || true

# Fix Log Permissions (Crucial for Docker containers running as non-root)
# qBittorrent (user 1000) needs to write to this folder
chmod -R 777 logs

 # Ensure Aria2 config exists with the correct hook
 if [ ! -f configs/aria2/aria2.conf ]; then
     echo "Creating default Aria2 config..."
     cat <<EOF > configs/aria2/aria2.conf
dir=/downloads
rpc-secret=${RPC_SECRET}
enable-rpc=true
rpc-listen-all=true
rpc-listen-port=6800
rpc-allow-origin-all=true
on-download-complete=/scripts/aria_manage.sh
input-file=/config/aria2.session
save-session=/config/aria2.session
save-session-interval=60
force-save=true
log=/logs/aria2.log
log-level=notice
EOF
 else
     # Update existing config if hook is missing
     if ! grep -q "on-download-complete" configs/aria2/aria2.conf; then
         echo "on-download-complete=/scripts/aria_manage.sh" >> configs/aria2/aria2.conf
         echo "Updated Aria2 config with automation hook."
     fi
 fi

# Fix ownership of all configs
chown -R "$CURRENT_USER:$CURRENT_USER" configs logs scripts

# Pre-Create JDownloader Configs to prevent Startup Crash in Headless Mode
echo -e "\n${BLUE}Pre-configuring JDownloader...${NC}"
mkdir -p configs/jdownloader/cfg

# 1. Create GUI Settings file (Prevents 'jq: error' during container init)
if [ ! -f "configs/jdownloader/cfg/org.jdownloader.settings.GraphicalUserInterfaceSettings.json" ]; then
    # We disable the tray icon to prevent the "Tray isn't supported" error on startup
    echo '{"trayiconenabled": false}' > configs/jdownloader/cfg/org.jdownloader.settings.GraphicalUserInterfaceSettings.json
fi

# 2. Set Default Download Path to /downloads
if [ ! -f "configs/jdownloader/cfg/org.jdownloader.settings.GeneralSettings.json" ]; then
    echo '{"defaultdownloadfolder" : "/downloads"}' > configs/jdownloader/cfg/org.jdownloader.settings.GeneralSettings.json
fi

# 3. Inject Pre-Installed Extensions (Snapshot Deployment)
# The user provided a zip of pre-installed extensions to bypass the manual "Install Now" step.
EXTENSIONS_URL="https://github.com/tvkk0539/Rclone-Arr-Setup-with-jules-customised/releases/download/v1/jdownloader_extensions.zip"
EXTENSIONS_DIR="configs/jdownloader/extensions"

echo -e "${BLUE}Downloading JDownloader Extensions...${NC}"
mkdir -p "$EXTENSIONS_DIR"

if wget -qO /tmp/jd_extensions.zip "$EXTENSIONS_URL"; then
    echo "Extracting extensions..."
    # We use -j to flatten the directory structure and extract only .jar files
    unzip -o -q -j /tmp/jd_extensions.zip "*.jar" -d "$EXTENSIONS_DIR"
    rm /tmp/jd_extensions.zip
    echo -e "${GREEN}Extensions pre-installed successfully.${NC}"

    # 4. Pre-Enable Event Scripter
    # Since we installed the JAR, we can safe-enable it immediately.
    # This prevents the race condition where JDownloader starts, sees the new JAR, and defaults it to "Disabled".
    JD_EXT_FILE="configs/jdownloader/cfg/org.jdownloader.extensions.eventscripter.EventScripterExtension.json"
    if [ ! -f "$JD_EXT_FILE" ]; then
        echo '{"enabled":true}' > "$JD_EXT_FILE"
        echo "Auto-enabled Event Scripter Extension."
    fi
else
    echo -e "${YELLOW}Failed to download extensions. You may need to install them manually.${NC}"
fi

# Fix specific permissions for JDownloader (Container runs as user 1000)
chown -R 1000:1000 configs/jdownloader

# 6. Rclone Config Setup
echo -e "\n${GREEN}[5/7] Setting up Rclone Config...${NC}"
CONFIG_FILE="configs/rclone/rclone.conf"

if [ -f "$CONFIG_FILE" ]; then
    echo -e "${BLUE}Existing rclone.conf found. Skipping setup.${NC}"
else
    echo -e "${YELLOW}No rclone.conf found.${NC}"
    echo "1) I have an existing rclone.conf content (Paste it)"
    echo "2) I want to run the Config Wizard (Create New)"
    read -p "Select option [1/2]: " OPTION

    if [ "$OPTION" == "1" ]; then
        echo -e "${YELLOW}Paste your config content below. Press Ctrl+D when finished:${NC}"
        cat > "$CONFIG_FILE"
        echo -e "${GREEN}Config saved to: $REPO_ROOT/$CONFIG_FILE${NC}"
    else
        echo -e "${BLUE}Starting Rclone Wizard...${NC}"
        echo -e "${YELLOW}IMPORTANT: If asked for auto-config, say NO (n) because this is a headless server.${NC}"
        # We run this as the sudo user to avoid permission issues with the created file
        docker run --rm -it -v "$REPO_ROOT/configs/rclone:/config/rclone" rclone/rclone config --config /config/rclone/rclone.conf
        echo -e "${GREEN}Config saved to: $REPO_ROOT/$CONFIG_FILE${NC}"
    fi
fi

# Fix config permissions
chown "$CURRENT_USER:$CURRENT_USER" "$CONFIG_FILE" 2>/dev/null

# Smart Fix: Check if Remote Name matches Config
# We grep the first line starting with '[' to find the actual remote name in the file
ACTUAL_REMOTE_NAME=$(grep -m 1 "^\[" "$CONFIG_FILE" | tr -d '[]')

if [ ! -z "$ACTUAL_REMOTE_NAME" ] && [ "$ACTUAL_REMOTE_NAME" != "$RCLONE_REMOTE" ]; then
    echo -e "\n${YELLOW}WARNING: Mismatch detected!${NC}"
    echo "You entered remote name: '$RCLONE_REMOTE'"
    echo "But your config file has: '$ACTUAL_REMOTE_NAME'"
    echo -e "${GREEN}Auto-correcting .env file to use '$ACTUAL_REMOTE_NAME'...${NC}"

    # Update .env using sed
    sed -i "s/RCLONE_REMOTE=$RCLONE_REMOTE/RCLONE_REMOTE=$ACTUAL_REMOTE_NAME/" .env

    # Update our variable for the script execution
    RCLONE_REMOTE=$ACTUAL_REMOTE_NAME
fi

# 7. Start Services
echo -e "\n${GREEN}[6/7] Starting Services...${NC}"

# Create network if not exists
if ! docker network inspect nginx_network &>/dev/null; then
    docker network create nginx_network
    echo -e "Created docker network: nginx_network"
fi

# Service Selection Logic
CORE_SERVICES="rclone"
OPTIONAL_SERVICES=("homarr" "radarr" "prowlarr" "qbittorrent" "aria2" "ariang" "jellyseerr" "profilarr" "jellyfin" "jdownloader")

echo -e "\n${BLUE}Installation Mode:${NC}"
echo "1) Full Installation (Install Everything)"
echo "2) Custom Installation (Select apps to SKIP)"
echo "3) Selective Installation (Select apps to INSTALL)"
read -p "Select option [1]: " INSTALL_MODE

if [ "$INSTALL_MODE" == "2" ]; then
    echo -e "\n${YELLOW}Custom Installation (SKIP Mode).${NC}"
    echo "The following core services will ALWAYS be installed: $CORE_SERVICES"
    echo -e "\nSelect the apps you do NOT want to install:"

    # List optional services
    for i in "${!OPTIONAL_SERVICES[@]}"; do
        echo "$((i+1)). ${OPTIONAL_SERVICES[$i]}"
    done

    echo -e "\nEnter the numbers of the apps to SKIP (separated by space)."
    echo "Example: To skip Radarr and Homarr, type: 1 2"
    read -p "Skip apps: " SKIP_INDICES

    # Build list of services to run
    SERVICES_TO_RUN="$CORE_SERVICES"

    # Loop through all optional services
    for i in "${!OPTIONAL_SERVICES[@]}"; do
        SERVICE_NUM=$((i+1))
        SERVICE_NAME="${OPTIONAL_SERVICES[$i]}"

        # Check if this index was skipped
        # We add spaces around the list to match whole numbers (e.g. avoid matching '1' inside '10')
        if [[ " $SKIP_INDICES " =~ " $SERVICE_NUM " ]]; then
            echo -e "${RED}Skipping $SERVICE_NAME${NC}"
        else
            SERVICES_TO_RUN="$SERVICES_TO_RUN $SERVICE_NAME"
            echo -e "${GREEN}Adding $SERVICE_NAME${NC}"
        fi
    done

    # Auto-include mount if jellyfin is selected
    if [[ "$SERVICES_TO_RUN" == *"jellyfin"* ]]; then
         SERVICES_TO_RUN="$SERVICES_TO_RUN mount"
         echo -e "${GREEN}Auto-enabling Rclone Mount (Required for Jellyfin)${NC}"
    fi

    echo -e "\nStarting specific services: $SERVICES_TO_RUN"
    docker compose up -d $SERVICES_TO_RUN

elif [ "$INSTALL_MODE" == "3" ]; then
    echo -e "\n${YELLOW}Selective Installation (INCLUDE Mode).${NC}"
    echo "The following core services will ALWAYS be installed: $CORE_SERVICES"
    echo -e "\nSelect the apps you WANT to install:"

    # List optional services
    for i in "${!OPTIONAL_SERVICES[@]}"; do
        echo "$((i+1)). ${OPTIONAL_SERVICES[$i]}"
    done

    echo -e "\nEnter the numbers of the apps to INSTALL (separated by space)."
    echo "Example: To install only Homarr and qBittorrent, type: 1 4"
    read -p "Install apps: " INCLUDE_INDICES

    # Build list of services to run
    SERVICES_TO_RUN="$CORE_SERVICES"

    # Loop through all optional services
    for i in "${!OPTIONAL_SERVICES[@]}"; do
        SERVICE_NUM=$((i+1))
        SERVICE_NAME="${OPTIONAL_SERVICES[$i]}"

        # Check if this index was selected
        # We add spaces around the list to match whole numbers (e.g. avoid matching '1' inside '10')
        if [[ " $INCLUDE_INDICES " =~ " $SERVICE_NUM " ]]; then
            SERVICES_TO_RUN="$SERVICES_TO_RUN $SERVICE_NAME"
            echo -e "${GREEN}Adding $SERVICE_NAME${NC}"
        else
            echo -e "${RED}Skipping $SERVICE_NAME${NC}"
        fi
    done

    # Auto-include mount if jellyfin is selected
    if [[ "$SERVICES_TO_RUN" == *"jellyfin"* ]]; then
         SERVICES_TO_RUN="$SERVICES_TO_RUN mount"
         echo -e "${GREEN}Auto-enabling Rclone Mount (Required for Jellyfin)${NC}"
    fi

    echo -e "\nStarting specific services: $SERVICES_TO_RUN"
    docker compose up -d $SERVICES_TO_RUN

else
    echo -e "\n${GREEN}Starting ALL services...${NC}"
    docker compose up -d
fi

# 8. Post-Deployment Automation (JDownloader)
# We check if JDownloader is running and inject the automation script if needed.
if docker compose ps --services --filter "status=running" | grep -q "jdownloader"; then
    echo -e "\n${BLUE}[Auto-Config] Checking JDownloader Automation...${NC}"
    JD_CONFIG_DIR="configs/jdownloader/cfg"
    JD_CONFIG_FILE="$JD_CONFIG_DIR/org.jdownloader.settings.GraphicalUserInterfaceSettings.json"
    JD_SCRIPT_FILE="$JD_CONFIG_DIR/org.jdownloader.extensions.eventscripter.EventScripterExtension.scripts.json"

    # Wait for JDownloader to initialize its config files (max 180 seconds)
    echo -n "Waiting for JDownloader to initialize..."
    for i in $(seq 1 36); do
        if [ -f "$JD_CONFIG_FILE" ]; then
            echo -e " ${GREEN}Done.${NC}"

            # Check if automation script needs injection
            if [ ! -f "$JD_SCRIPT_FILE" ]; then
                echo "Injecting Rclone Upload script..."
                # We stop JD to safely inject the script (though technically less critical for scripts, good practice)
                docker compose stop jdownloader

                cat <<EOF > "$JD_SCRIPT_FILE"
[
  {
    "eventTrigger": "ON_PACKAGE_FINISHED",
    "enabled": true,
    "name": "Rclone Upload",
    "script": "var script = \"/scripts/jd_manage.sh\";\nvar path = package.getDownloadFolder();\nvar name = package.getName();\ncallAsync(function() {}, script, name, path);",
    "eventTriggerSettings": {},
    "id": 1698745632145
  }
]
EOF

                # Fix permissions (Must be user 1000 for JDownloader)
                chown -R 1000:1000 "$JD_CONFIG_DIR"

                # Restart JDownloader to load the new config
                # We used 'stop' earlier, so we use 'start' or 'up -d' here
                echo "Starting JDownloader to apply changes..."
                docker compose start jdownloader
                echo -e "${GREEN}JDownloader Automation Enabled!${NC}"
            else
                echo -e "${GREEN}Automation script already active.${NC}"
            fi
            break
        fi

        echo -n "."
        sleep 5
    done

    if [ ! -f "$JD_CONFIG_FILE" ]; then
        echo -e "\n${YELLOW}JDownloader is taking too long to start.${NC}"
        echo "Automation skipped. You can run 'sudo ./scripts/init_jd.sh' later."
    fi
fi

echo -e "\n${GREEN}[7/7] Deployment Complete!${NC}"

# Get External IP Address (for Google Cloud / VPS)
# We try to curl a public service. If it fails, we fall back to the internal IP.
PUBLIC_IP=$(curl -s https://api.ipify.org || hostname -I | awk '{print $1}')
IP_ADDRESS=${PUBLIC_IP:-localhost}

echo -e "\n${BLUE}=================================================${NC}"
echo -e "${BLUE}       Access Your Services                     ${NC}"
echo -e "${BLUE}=================================================${NC}"
echo -e "Homarr (Dashboard) : http://$IP_ADDRESS:7575"
echo -e "Jellyfin (Stream)  : http://$IP_ADDRESS:8096"
echo -e "Jellyseerr (Request): http://$IP_ADDRESS:5055"
echo -e "Radarr             : http://$IP_ADDRESS:7878"
echo -e "qBittorrent        : http://$IP_ADDRESS:8080"
echo -e "JDownloader 2      : http://$IP_ADDRESS:5800"
echo -e "AriaNg (Aria2 UI)  : http://$IP_ADDRESS:6880"
echo -e "Rclone WebUI       : http://$IP_ADDRESS:5572"
echo -e "${BLUE}=================================================${NC}"
echo -e "Login Credentials:"
echo -e "qBittorrent : admin / adminadmin"
echo -e "Rclone WebUI: $RCLONE_USER / $RCLONE_PASS"
echo -e "-------------------------------------------------"
echo -e "Generated Keys (Saved in .env):"
echo -e "Homarr Encryption Key: $HOMARR_KEY"
echo -e "Aria2 RPC Secret     : $RPC_SECRET"
echo -e "${BLUE}=================================================${NC}"
